const express = require('express');
const router = express.Router();

router.use('/inquiries', require('./inquiry'));
router.use('/products', require('./product'));
router.use('/customers', require('./customer'));
router.use('/materials', require('./material'));
router.use('/material-costs', require('./material-costs'));
router.use('/materials-ext', require('./material-ext'));
router.use('/procurement', require('./procurement'));
router.use('/suppliers', require('./supplier'));
router.use('/external-api', require('./external-api'));
router.use('/orders', require('./order'));
router.use('/samples', require('./sample'));
router.use('/projects', require('./project'));
router.use('/annual-plan', require('./annual-plan'));
router.use('/amiba', require('./amiba'));
router.use('/products/bom-types', require('./bom-type'));
router.use('/products/bom-issues', require('./bom-issue'));
router.use('/pricing', require('./pricing'));
router.use('/quote', require('./quote').router);
router.use('/users', require('./user'));
router.use('/reports', require('./report'));
router.use('/import', require('./import'));
router.use('/permissions', require('./permission'));
router.use('/feedback', require('./feedback'));
router.use('/settings', require('./settings'));
router.use('/test', require('./test'));
router.use('/compliance', require('./compliance'));
router.use('/configs', require('./config'));
router.use('/chat', require('./chat'));
router.use('/rules', require('./rules'));
router.use('/spec-library', require('./spec-library'));
router.use('/data-clean', require('./data-clean'));
router.use('/ai-assistant', require('./ai-assistant'));
router.use('/bom', require('./bom'));
router.use('/external-sync', require('./external-sync'));
router.use('/external', require('./external-service'));
router.use('/tech', require('./tech-transfer'));
router.use('/organization', require('./organization'));
router.use('/data-scope', require('./data-scope'));
router.use('/material-check', require('./material-check'));
router.use('/expenses', require('./expense'));
router.use('/labor', require('./labor'));
router.use('/product-labor-rate', require('./product-labor-rate'));
router.use('/material-issues', require('./material-issue'));
router.use('/order-analysis', require('./order-analysis'));

router.use('/order-check', require('./order-check'));

router.use('/sop', require('./sop'));
router.use('/im', require('./im'));

module.exports = router;
